name: Call Feature Flags Project Workflow

on:
    pull_request:
        types: [opened, ready_for_review, review_requested, synchronize, converted_to_draft, reopened]

jobs:
    call-flags-project:
        uses: haacked-demos/.github/.github/workflows/flags-project-board.yml@main
        with:
            pr_number: ${{ github.event.pull_request.number }}
            pr_node_id: ${{ github.event.pull_request.node_id }}
            is_draft: ${{ github.event.pull_request.draft }}
        secrets: inherit